name: DocumentFinder Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Install packages (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install xvfb tigervnc-standalone-server tigervnc-common
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Tests (Linux)
        if: runner.os == 'Linux'
        run: |
          export DISPLAY=:90
          mkdir /home/runner/.vnc
          echo 123456 | vncpasswd -f > /home/runner/.vnc/passwd
          chmod -v 600 /home/runner/.vnc/passwd
          vncserver :90 -localhost -nolisten tcp
          ./gradlew build test
          vncserver -kill :90

      - name: Upload test result
        uses: actions/upload-artifact@v3
        if: always
        with:
          name: test-reports
          path: /home/runner/work/document-finder/document-finder/build/reports/tests/test/
          retention-days: 20
