name: Build Debian *.deb

on:
  release:
    types: [published]

env:
  JAVA_VERSION: 25
  JAVA_DISTRIBUTION: 'zulu'

jobs:

  build:
    name: Build Document-Finder for Debian
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
          java-package: 'jdk'
          architecture: x64
          cache: 'gradle'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build
        run: ./gradlew jpackage
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: DocumentFinder.deb
          path: build/jpackage/*.deb
          if-no-files-found: error
      - name: Publish dmg on GitHub Releases
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          fail_on_unmatched_files: true
          files: |
            build/jpackage/*.deb
